# Generated by Django 4.1.5 on 2023-01-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertasCrise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_alerta', models.CharField(choices=[('P', 'Pânico'), ('A', 'Ansiedade'), ('D', 'Depressão')], max_length=1)),
                ('horario_acontecimento', models.DateTimeField()),
                ('horario_superou_crise', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('celular', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
