# Generated by Django 4.1.5 on 2023-01-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crise', '0002_alter_contato_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertascrise',
            name='horario_acontecimento',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='alertascrise',
            name='horario_superou_crise',
            field=models.TimeField(),
        ),
    ]
