# Generated by Django 4.1.5 on 2023-02-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crise', '0005_alter_alertascrise_horario_acontecimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertascrise',
            name='horario_acontecimento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='alertascrise',
            name='horario_superou_crise',
            field=models.DateTimeField(),
        ),
    ]
